version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      time: 01:00
    commit-message:
      prefix: NuGet packages
    labels: [ dependencies ]
    assignees: [ beauchama ]
    groups:
      all:
        patterns:
          - "*"
