version: 2
updates:
  - package-ecosystem: github-actions
    target-branch: develop
    directory: /
    schedule:
      interval: weekly
      day: sunday
    commit-message:
      prefix: "GitHub Actions"
    labels: [ dependencies ]
    assignees: [ beauchama ]
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: nuget
    target-branch: develop
    directories:
      - /src
      - /tests
    schedule:
      interval: daily
    commit-message:
      prefix: NuGet packages
    labels: [ dependencies ]
    assignees: [ beauchama ]
    groups:
      dotnet:
        patterns:
          - "*"

  - package-ecosystem: nuget
    target-branch: develop
    directories:
      - /.config
    schedule:
      interval: daily
    commit-message:
      prefix: Dotnet tools
    labels: [ dependencies ]
    assignees: [ beauchama ]
    groups:
      dotnet-tools:
        patterns:
          - "*"
