name: Staging

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy

    permissions:
      contents: read
      deployments: write

    uses: wavepulse/atlas/.github/workflows/publish.yml@main
    with:
      branch: main
      environment: production
    secrets: inherit
