name: Production

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Production environment

    permissions:
      contents: read
      deployments: write

    uses: wavepulse/atlas/.github/workflows/setup.yml@main
    with:
      branch: main
      environment: production
    secrets: inherit