name: Staging

on:
  workflow_dispatch:
  push:
    branches: [ develop ]

jobs:
  deploy:
    name: Deploy
    uses: wavepulse/atlas/.github/workflows/publish.yml@develop
    with:
      branch: develop
      environment: staging
    secrets: inherit
