name: Staging

on:
  workflow_dispatch:
  push:
    branches: [ develop ]

jobs:
  staging:
    name: Staging environment

    permissions:
      contents: read
      deployments: write

    uses: wavepulse/atlas/.github/workflows/setup.yml@develop
    with:
      branch: develop
      environment: staging
    secrets: inherit